
name: deploy site on git push
on: [push]
jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #     - run: docker build .

  deploy:
    #needs: build 
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }} #ssh key
        port: ${{ secrets.PORT }}
        script: |
          echo "running update script: ${{ secrets.SCRIPT_TO_RUN }}"
          ${{ secrets.SCRIPT_TO_RUN }}
